package interfaz.Configuraciones;

import Otros.Configuraciones.Configuracion;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author W.O.R.A.
 *
 */
public class FrmInitConfig extends javax.swing.JDialog {

    boolean inicio = false;

    public FrmInitConfig(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        txtvalorDolar = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txtBDLocal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtUserLocal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbTpoConexionLocal = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnTestLocal = new javax.swing.JButton();
        txtPassLocal = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        txtUserWeb = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtUrlWeb = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBDWeb = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        btnTestWeb = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtPassWeb = new javax.swing.JPasswordField();
        txtvalorGasOil = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtconfigFletes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Iniciar configuración del sistema");
        setIconImage(Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("interfaz/iconos/edit-find.png")));
        setMinimumSize(new java.awt.Dimension(710, 450));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Valor dólar:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 70, 77, 20);

        txtvalorDolar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvalorDolarKeyTyped(evt);
            }
        });
        getContentPane().add(txtvalorDolar);
        txtvalorDolar.setBounds(260, 70, 220, 19);

        jLabel21.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel21.setText("Campos Obligatorios (*)");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(20, 390, 230, 15);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/iconos/Button White Load.png"))); // NOI18N
        btnModificar.setText("Iniciar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(320, 380, 120, 30);

        jPanel1.setBackground(new java.awt.Color(153, 180, 209));
        jPanel1.setPreferredSize(new java.awt.Dimension(580, 71));

        jLabel15.setBackground(new java.awt.Color(51, 255, 51));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Configurar sistema");
        jLabel15.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel15)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Base de datos local", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel2.setToolTipText("Configuración base de datos local");
        jPanel2.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Local", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel3.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("*");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(290, 120, 10, 15);
        jPanel3.add(txtBDLocal);
        txtBDLocal.setBounds(140, 120, 140, 19);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Base de datos: ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 120, 100, 15);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Password: ");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(10, 90, 68, 15);
        jPanel3.add(txtUserLocal);
        txtUserLocal.setBounds(140, 60, 140, 19);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Usuario :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 60, 56, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Tipo de conexion :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 30, 120, 20);

        cbTpoConexionLocal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ODBC", "Manual" }));
        cbTpoConexionLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTpoConexionLocalActionPerformed(evt);
            }
        });
        jPanel3.add(cbTpoConexionLocal);
        cbTpoConexionLocal.setBounds(140, 30, 140, 24);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("*");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(290, 30, 10, 15);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("*");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(290, 60, 10, 15);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("*");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(290, 90, 10, 15);

        btnTestLocal.setText("Test");
        btnTestLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestLocalActionPerformed(evt);
            }
        });
        jPanel3.add(btnTestLocal);
        btnTestLocal.setBounds(130, 170, 70, 30);
        jPanel3.add(txtPassLocal);
        txtPassLocal.setBounds(140, 90, 140, 19);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 20, 320, 210);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Web", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel5.setLayout(null);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText("*");
        jPanel5.add(jLabel36);
        jLabel36.setBounds(290, 110, 10, 15);
        jPanel5.add(txtUserWeb);
        txtUserWeb.setBounds(140, 80, 140, 19);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Password: ");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(20, 110, 68, 15);
        jPanel5.add(txtUrlWeb);
        txtUrlWeb.setBounds(140, 50, 140, 19);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Url:");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(20, 50, 21, 15);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setText("*");
        jPanel5.add(jLabel37);
        jLabel37.setBounds(290, 20, 10, 15);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setText("*");
        jPanel5.add(jLabel38);
        jLabel38.setBounds(290, 50, 10, 15);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel39.setText("*");
        jPanel5.add(jLabel39);
        jLabel39.setBounds(290, 80, 10, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Usuario :");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(20, 80, 56, 15);
        jPanel5.add(txtBDWeb);
        txtBDWeb.setBounds(140, 140, 140, 19);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Base de datos: ");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(20, 140, 110, 15);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel40.setText("*");
        jPanel5.add(jLabel40);
        jLabel40.setBounds(290, 140, 10, 15);

        btnTestWeb.setText("Test");
        btnTestWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestWebActionPerformed(evt);
            }
        });
        jPanel5.add(btnTestWeb);
        btnTestWeb.setBounds(130, 170, 70, 30);

        jCheckBox1.setText("Tiene conexion web:");
        jPanel5.add(jCheckBox1);
        jCheckBox1.setBounds(70, 20, 180, 23);
        jPanel5.add(txtPassWeb);
        txtPassWeb.setBounds(140, 110, 140, 19);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(350, 20, 320, 210);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 130, 680, 240);

        txtvalorGasOil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvalorGasOilKeyTyped(evt);
            }
        });
        getContentPane().add(txtvalorGasOil);
        txtvalorGasOil.setBounds(260, 100, 220, 19);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Valor gasoil:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(180, 100, 77, 20);

        txtconfigFletes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtconfigFletesKeyTyped(evt);
            }
        });
        getContentPane().add(txtconfigFletes);
        txtconfigFletes.setBounds(260, 40, 220, 19);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Configuración de fletes cortos:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 40, 200, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtvalorDolarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorDolarKeyTyped
        char caracter = evt.getKeyChar();
        String text = txtvalorDolar.getText();
        if (caracter == '.') {
            if (text.equals("") || text.contains(".")) {
                evt.consume();
            }
        } else if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (text.length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtvalorDolarKeyTyped

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        if (comprobarCampos("todos")) {
            double valorDolar = Double.parseDouble(txtvalorDolar.getText());
            double valorGasOil = Double.parseDouble(txtvalorGasOil.getText());
            int configFletes = Integer.parseInt(txtconfigFletes.getText());
            Configuracion.getInstance().modificarConfiguraciones(valorDolar, valorGasOil, configFletes,
                    cbTpoConexionLocal.getSelectedItem().toString(), txtUserLocal.getText(), txtPassLocal.getText(), txtBDLocal.getText(),
                    jCheckBox1.isSelected(), txtUrlWeb.getText(), txtUserWeb.getText(), txtPassWeb.getText(), txtBDWeb.getText());
            if (Configuracion.getInstance().modificar()) {
                inicio = true;
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Faltaron ingresar datos obligatorios", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (!inicio) {
            System.exit(1);
        }
    }//GEN-LAST:event_formWindowClosing

    private void cbTpoConexionLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTpoConexionLocalActionPerformed
        String tpo = cbTpoConexionLocal.getSelectedItem().toString();
        if (tpo.equals("ODBC")) {
            txtUserLocal.setText("");
            txtUserLocal.setEnabled(false);
            txtPassLocal.setText("");
            txtPassLocal.setEnabled(false);
            txtBDLocal.setText("");
            txtBDLocal.setEnabled(false);
        } else {
            txtUserLocal.setEnabled(true);
            txtPassLocal.setEnabled(true);
            txtBDLocal.setEnabled(true);
        }
    }//GEN-LAST:event_cbTpoConexionLocalActionPerformed

    private void btnTestLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestLocalActionPerformed
        if (comprobarCampos("basededatoslocal")) {
            JOptionPane.showMessageDialog(null, "Conexion exitosa", ":-)",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnTestLocalActionPerformed

    private void btnTestWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestWebActionPerformed
        if (comprobarCampos("basededatosweb")) {
            JOptionPane.showMessageDialog(null, "Conexion exitosa", ":-)",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnTestWebActionPerformed

    private void txtvalorGasOilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorGasOilKeyTyped
        char caracter = evt.getKeyChar();
        String text = txtvalorGasOil.getText();
        if (caracter == '.') {
            if (text.equals("") || text.contains(".")) {
                evt.consume();
            }
        } else if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (text.length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtvalorGasOilKeyTyped

    private void txtconfigFletesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfigFletesKeyTyped
        char caracter = evt.getKeyChar();
        String text = txtconfigFletes.getText();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (text.length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtconfigFletesKeyTyped

    public boolean comprobarCampos(String comp) {
        if (comp.equals("todos")) {
            try {
                double valorDolar = Double.parseDouble(txtvalorDolar.getText());
                double valorGasOil = Double.parseDouble(txtvalorGasOil.getText());
                int configFletes = Integer.parseInt(txtconfigFletes.getText());
                if (valorDolar == 0 || valorGasOil == 0 || configFletes == 0) {
                    return false;
                }
            } catch (Exception e) {
                return false;
            }
        }
        if (comp.equals("todos") || comp.equals("basededatoslocal")) {
            if (!cbTpoConexionLocal.getSelectedItem().toString().equals("ODBC")) {
                if (txtUserLocal.getText().equals("") || txtBDLocal.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Faltaron ingresar datos obligatorios", "Error",
                            JOptionPane.INFORMATION_MESSAGE);
                    return false;
                }
            }
            if (!testConLocal()) {
                return false;
            }

        } else if (comp.equals("todos") || comp.equals("basededatosweb")) {
            if (jCheckBox1.isSelected()) {
                if (txtUrlWeb.getText().equals("") || txtUserWeb.getText().equals("") || txtBDWeb.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Faltaron ingresar datos obligatorios", "Error",
                            JOptionPane.INFORMATION_MESSAGE);
                    return false;
                }
                if (!testConWeb()) {
                    return false;
                }
            }
        }
        return true;
    }

    public boolean testConLocal() {
        Connection conLocal = null;
        String tpo = cbTpoConexionLocal.getSelectedItem().toString();
        try {
            if (conLocal == null || conLocal.isClosed()) {
                if (tpo.equals("ODBC")) {
                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    if (/*WORATransportes.IsTerminal()*/false) {
                        conLocal = DriverManager.getConnection("jdbc:odbc:bd2Terminal");
                    } else {
                        conLocal = DriverManager.getConnection("jdbc:odbc:bd2");
                    }
                } else if (tpo.equals("Manual")) {
                    String user = txtUserLocal.getText();
                    String password = txtPassLocal.getText();
                    String bd = txtBDLocal.getText();
                    String url = "jdbc:mysql://127.0.0.1/" + bd;
                    Class.forName("com.mysql.jdbc.Driver");
                    conLocal = DriverManager.getConnection(url, user, password);
                }
            }
        } catch (Exception e) {
            conLocal = null;
        }
        if (conLocal != null) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Error en la conexion", ":-(",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    public boolean testConWeb() {
        Connection conWeb = null;
        try {
            if (conWeb == null || conWeb.isClosed()) {
                if (jCheckBox1.isSelected()) {
                    String user = txtUserWeb.getText();
                    String password = txtPassWeb.getText();
                    String bd = txtBDWeb.getText();
                    String url = "jdbc:mysql://" + txtUrlWeb.getText() + "/" + bd;
                    Class.forName("com.mysql.jdbc.Driver");
                    conWeb = DriverManager.getConnection(url, user, password);
                }
            }
        } catch (Exception e) {
            conWeb = null;
        }
        if (conWeb == null) {
            JOptionPane.showMessageDialog(null, "Error en la conexion", ":-(",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnTestLocal;
    private javax.swing.JButton btnTestWeb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbTpoConexionLocal;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtBDLocal;
    private javax.swing.JTextField txtBDWeb;
    private javax.swing.JPasswordField txtPassLocal;
    private javax.swing.JPasswordField txtPassWeb;
    private javax.swing.JTextField txtUrlWeb;
    private javax.swing.JTextField txtUserLocal;
    private javax.swing.JTextField txtUserWeb;
    private javax.swing.JTextField txtconfigFletes;
    private javax.swing.JTextField txtvalorDolar;
    private javax.swing.JTextField txtvalorGasOil;
    // End of variables declaration//GEN-END:variables
}
